version: '3'
services:
  flask:
    build: .
        # equivalent to -it in docker run command (needed for react app)
    container_name: flask
#    network_mode: host
    #        networks:
    #            rest-network:
    #               aliases:
    #                  - reverse-proxy
    ports:
      - 8001:8001
    volumes:
      - ./:/app/